from pydantic import BaseModel, Field
from typing import Optional

class SystemNode(BaseModel):
    tenant_id: str = Field(..., description="Unique identifier for the tenant system")
    name: Optional[str] = None

class AscentNode(BaseModel):
    t_star: int = Field(..., description="The time index where the critical mass was breached")
    tau: float = Field(..., description="The tau correlation value at the transition")
    description: str = Field(..., description="Details about the ontological transition")
    timestamp: Optional[int] = Field(None, description="Unix timestamp of the transition")

class ReportNode(BaseModel):
    content: str = Field(..., description="The generated LaTeX report from the LLM.")
    timestamp: Optional[int] = Field(None, description="Unix timestamp of generation")

class HypothesisNode(BaseModel):
    claim: str = Field(..., description="The causal claim generated by the Hypothesizer Agent")
    confidence: float = Field(..., description="Confidence score from the Critic Agent")
    timestamp: Optional[int] = Field(None, description="Unix timestamp of hypothesis generation")

class EvidenceNode(BaseModel):
    source: str = Field(..., description="External tool or database used (e.g. PubMed, FinAPI)")
    data_summary: str = Field(..., description="Summary of the empirical evidence fetched")
    supports_hypothesis: bool = Field(..., description="True if evidence corroborates the claim, False if it refutes it")

class ToolNode(BaseModel):
    name: str = Field(..., description="Name of the tool (e.g. PubMedSearchTool)")
    version: str = Field(default="1.0", description="Version of the tool used")

class TheoryNode(BaseModel):
    unified_claim: str = Field(..., description="The synthesized theory across multiple corroborated hypotheses")
    confidence: float = Field(..., description="Aggregated confidence score")
    timestamp: Optional[int] = Field(None, description="Unix timestamp of theory synthesis")

class UniversalTheoryNode(BaseModel):
    macro_claim: str = Field(..., description="A cross-domain unified field theory spanning multiple isolated complex systems")
    isomorphisms_found: int = Field(default=0, description="Number of distinct domains sharing the exact mathematical phase transition")
    confidence: float = Field(..., description="Adversarial consensus score across multiple agent societies")
    timestamp: Optional[int] = Field(None, description="Unix timestamp of macro-theory synthesis")
